"""Generate checkpoints.md (audit write-up) from checkpoints.json."""

import json
import re
from collections import Counter

with open("checkpoints.json") as f:
    data = json.load(f)

RELEVANT = {
    # repo_id: (flow stage, role in project)
    "allenai/Olmo-3-1025-7B": ("Pretraining (7B base)", "E1 formation curves, primary"),
    "allenai/OLMo-2-0425-1B": ("Pretraining (1B early suite)", "E1 fine-grained early dynamics"),
    "allenai/Olmo-3-7B-Think-SFT": ("SFT (Think)", "E2 drift, fine-grained"),
    "allenai/Olmo-3-7B-Think-DPO": ("DPO (Think)", "E2 drift, endpoint only"),
    "allenai/Olmo-3-7B-Think": ("RLVR (Think)", "E2/E3, densest RL trajectory"),
    "allenai/Olmo-3-7B-Instruct-SFT": ("SFT (Instruct)", "E2 coarse replicate"),
    "allenai/Olmo-3-7B-Instruct-DPO": ("DPO (Instruct)", "E2 coarse replicate"),
    "allenai/Olmo-3-7B-Instruct": ("RLVR (Instruct)", "E2 coarse replicate"),
    "allenai/Olmo-3-7B-RL-Zero-Math": ("RL-Zero", "RQ2 aggressive setting"),
    "allenai/Olmo-3-7B-RL-Zero-Code": ("RL-Zero", "RQ2 aggressive setting"),
    "allenai/Olmo-3-7B-RL-Zero-IF": ("RL-Zero", "RQ2 aggressive setting"),
    "allenai/Olmo-3-7B-RL-Zero-Mix": ("RL-Zero", "RQ2 aggressive setting"),
    "allenai/Olmo-3-7B-RL-Zero-General": ("RL-Zero", "RQ2 aggressive setting"),
    "allenai/Olmo-3.1-7B-RL-Zero-Math": ("RL-Zero (3.1)", "RQ2, longer run"),
    "allenai/Olmo-3.1-7B-RL-Zero-Code": ("RL-Zero (3.1)", "RQ2, longer run"),
}


def stage_counts(branches):
    c = Counter()
    for b in branches:
        m = re.match(r"(stage\d+)", b)
        c[m.group(1) if m else "step"] += 1
    return ", ".join(f"{k}: {v}" for k, v in sorted(c.items()))


lines = [
    "# Checkpoint audit (2026-08-05)",
    "",
    "Full raw listing: `checkpoints.json` (generated by `scripts/audit_checkpoints.py`).",
    "Intermediates are git branches per repo; pin exact branch names as HF revisions in configs.",
    "",
    "## Relevant repos",
    "",
    "| Repo | Flow stage | Intermediates | Breakdown | Role |",
    "|---|---|---|---|---|",
]

for repo_id, (stage, role) in RELEVANT.items():
    branches = data.get(repo_id)
    if branches is None or isinstance(branches, str):
        lines.append(f"| {repo_id} | {stage} | MISSING | - | {role} |")
        continue
    non_main = [b for b in branches if b != "main"]
    lines.append(
        f"| {repo_id} | {stage} | {len(non_main)} | {stage_counts(non_main)} | {role} |"
    )

lines += [
    "",
    "## Scope implications",
    "",
    "- **Pretraining density is far better than planned**: Olmo-3-1025-7B has ~1,487",
    "  branches (stage1 approx. every 1k steps, plus stage2/stage3 anneal ingredients).",
    "  Plan assumed 10-15 log-spaced; we can choose them freely.",
    "- **The fine-grained post-training story runs through the Think pipeline**:",
    "  SFT 44 -> DPO 1 -> RLVR 56 (every 25 steps). Instruct is endpoint-SFT/DPO + 9 RL",
    "  steps: use as a coarse replicate, not the primary curve.",
    "- **DPO intermediates do not exist anywhere** (all DPO repos are endpoint-only).",
    "  Any claim about DPO must be endpoint-to-endpoint.",
    "- **RL-Zero is richly covered**: five domain variants (Math/Code/IF/Mix/General,",
    "  20-34 intermediates each) plus Olmo-3.1 Math (29) and Code (34) longer runs.",
    "  The RL-Zero vs full-flow comparison (RQ2) has plenty of resolution.",
    "- 32B lineage (Olmo-3-1125-32B, 32B-Think, Olmo-3.1-32B) exists with similar",
    "  density: an optional scale replication if compute allows; not in the 1-month scope.",
]

with open("checkpoints.md", "w") as f:
    f.write("\n".join(lines) + "\n")
print("wrote checkpoints.md")
